using System.Reflection;

// Company/Product/Title and the numeric Assembly/File versions are generated by the SDK
// from the MSBuild properties in LogGrokCore.csproj (Version is supplied by the release
// pipeline from the git tag). Only the git-based informational version is hand-written here.
[assembly: AssemblyInformationalVersion($"{ThisAssembly.Git.Branch}:{ThisAssembly.Git.Commit}")]
