name: Unit tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AVALONIA_TELEMETRY_OPTOUT: 1

jobs:

  windows_build_and_test:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore the application
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{matrix.configuration}} --no-restore

    - name: Execute unit tests
      run: dotnet test --configuration ${{matrix.configuration}} --no-restore --verbosity normal

  linux_build_and_test:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore data tests
      run: dotnet restore LogGrokCore.Data.Tests/LogGrokCore.Data.Tests.csproj

    - name: Build data tests
      run: dotnet build LogGrokCore.Data.Tests/LogGrokCore.Data.Tests.csproj --configuration ${{matrix.configuration}} --no-restore

    - name: Execute data tests
      run: dotnet test LogGrokCore.Data.Tests/LogGrokCore.Data.Tests.csproj --configuration ${{matrix.configuration}} --no-restore --no-build --verbosity normal

    - name: Restore Avalonia shell
      run: dotnet restore LogGrokCore.Avalonia/LogGrokCore.Avalonia.csproj

    - name: Build Avalonia shell
      run: dotnet build LogGrokCore.Avalonia/LogGrokCore.Avalonia.csproj --configuration ${{matrix.configuration}} --no-restore
